import React from 'react';
export const metadata = {
  title: 'Profile || next hero',
  description: 'Generated by create next app',
}
const Profile = () => {
  return (
    <div>
      <h1>Profile</h1>
    </div>
  );
};

export default Profile;