import React from 'react';
export const metadata = {
  title: 'About || next hero',
  description: 'Generated by create next app',
}

const AboutPage = () => {
  return (
    <div>
      <h1>About page</h1>
    </div>
  );
};

export default AboutPage;