import React from 'react';
export const metadata = {
  title: 'Add Product || next hero',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>
      <h1>add product</h1>
    </div>
  );
};

export default page;