import GetAllProducts from '@/Utils/GetAllProducts';
import React from 'react';
import ManageSingleProduct from './ManageProduct';
export const metadata = {
  title: 'Manage Product || next hero',
  description: 'Generated by create next app',
}

const ManageProduct = async () => {

  const products = await GetAllProducts();

  return (
    <div>
      <h1>manage product</h1>

     <ManageSingleProduct 
        products={products}></ManageSingleProduct> 
      

    </div>
  );
};

export default ManageProduct;