import React from 'react';
export const metadata = {
  title: 'Manage Product || next hero',
  description: 'Generated by create next app',
}

const ManageProduct = () => {
  return (
    <div>
      <h1>manage product</h1>
    </div>
  );
};

export default ManageProduct;