import React from 'react';
export const metadata = {
  title: 'Dashboard || next hero',
  description: 'Generated by create next app',
}
const Dashboard = () => {
  return (
    <div>
      <h1>Dashboard</h1>
    </div>
  );
};

export default Dashboard;